# compilateur 
CC=gcc
# option
CFLAGS= -g -Wall -Wextra

# règle de production finale du TP 
main:main.o
	@$(CC) -o prog main.o
# règle qui efface l'exécutable et les fichiers objets
clean:
	@rm -rf prog main.o







	
